### ISSUE TITLE
prefix function names ?

### ISSUE THREAD

**Issue by asafyish** [babel-plugins/babel-plugin-incremental-dom#18]
Is it possible to prefix the generated function names ?
something like:
elementOpen to {prefix}elementOpen

The use case is, I want to have a global IncrementalDom object, instead of importing it in each module, and then set the prefix to 'IncrementalDom.' so it will transform jsx to:
IncrementalDom.elementOpen (and all the other element*).

**Comment by jridgewell** [comment]
We were actually waiting for plugin options so we could support arbitrary prefixes, but I'm not sure when Babel will support it. I think @jayphelps was going to work on adding `IncrementalDOM.` to all the function calls in the meantime.

**Comment by jridgewell** [comment]
Done, just add the `extra` options when using babel:

```json
{
  "blacklist": ["react"],
  "plugins": ["incremental-dom"],
  "extra": {
    "incremental-dom": {
      "prefix": "IncrementalDOM"
    }
  }
}
```
