### ISSUE TITLE
{Child AssignmentExpressions}

### ISSUE THREAD

**Issue by thejameskyle** [babel-plugins/babel-plugin-incremental-dom#8]
Originally raised in #5 ([start here](https://github.com/babel-plugins/babel-plugin-incremental-dom/pull/5#issuecomment-124945873))

### Issue

Simply put, there is no direct translation for the following in iDOM:

```js
let foo = <span>foo</span>;

<div>{foo}</div>
```

The output would currently result in:

```js
let foo = (elementOpen('span'), text('foo'), elementClose('span'));

elementOpen('div');
foo;
elementClose('div');
```

Or better put:

```html
<span>foo</span>
<div></div>
```

### Solution

To get around this, one potential solution is to wrap jsx elements in shadow functions (arrow functions).

```js
let foo = () => <span>foo</span>;

<div>{foo()}</div>
```

There's a couple of things to note here:
- We have to handle other types of `{}` such as arrays or text nodes.
- We don't want the second jsx block to be wrapped as it needs to be run at some point

In order to get around this we'll need to introduce a helper and a way of inferring you want the final block to not be wrapped.

#### Helper

```js
function runtimeInsert(value) {
  if (value instanceof Array) {
    value.forEach(runtimeInsert);
  } else if (value instanceof Function) {
    value();
  } else {
    text('' + value);
  }
}
```

#### Return Statements

Since the following is an example of how JSX is mostly used today, it makes sense to use ReturnStatement's as a way of deciding when not to wrap JSX in a shadow function.

```js
const heading = <h1>Hello</h1>;

class Component {
  render() {
    let items = [1, 2, 3].map(n =>
      <li>{n}</li>
    );

    return (
      <div>
        {heading}
        <ul>
          {items}
        </ul>
      </div
    );
  }
}
```

translated to:

```js
function runtimeInsert(value) {
  if (value instanceof Array) {
    value.forEach(runtimeInsert);
  } else if (value instanceof Function) {
    value();
  } else {
    text('' + value);
  }
}

const heading = () => <h1>Hello</h1>;

class Component {
  render() {
    let items = [1, 2, 3].map(n => {
      return () => {
        elementOpen('li');
        runtimeInsert(n);
        elementClose('li');
      };
    });

    return (
      elementOpen('div'),
      runtimeInsert(heading),
      elementOpen('ul'),
      runtimeInsert(items),
      elementClose('ul'),
      elementClose('div')
    );
  }
}
```

### Potential issues

If a user does not follow the `return <div/>` pattern, their code won't run which may confuse people (although I feel this won't be a huge one).

**Incorrect**
```js
function render() {
  <div></div>
}
patch(document.body, render);
```

**Correct**
```js
function render() {
  return <div></div>
}
patch(document.body, render);
```

**Correct**
```js
patch(document.body, <div></div>);
```

Although, hopefully most devs are used to this from React.

### Other solutions

JSX-IR gets around this by translating JSX into large nested objects wrapped in a runtime.

```js
<div className="box">
  <List>...</List>
</div>
```
```js
({
  tag: "div",
  props: {
    className: "box"
  },
  children: [{
    tag: "List",
    props: null,
    children: [...]
  }]
})
```

This is not the right solution as it eliminates most of the benefits of using iDOM in terms of memory and performance.

**Comment by jridgewell** [comment]
The helper looks good to me. But I feel icky creating a bunch of functions.

We can optimize the shadow functions by only creating them for expressions that are outside the returned one.

```js
// Will create shadow functions for the map.
function render() {
    let items = [1, 2, 3].map(n =>
      <li>{n}</li>
    );

    return (
        <ul>
          {items}
        </ul>
    );
}

// Won't create shadow functions for the map.
function render() {
    return (
        <ul>
          {
              let items = [1, 2, 3].map(n =>
                  <li>{n}</li>
              );
          }
        </ul>
    );
}

- - -

As a side, I wanted to highlight why I think JSX-IR is the wrong approach. From the [announcement post](https://medium.com/google-developers/introducing-incremental-dom-e98f79ce2c5f#73a2): 

> Inherent to this [virtual DOM] approach is that a new virtual DOM tree is allocated for each render operations that is at least big enough to hold the nodes that changed and often a bit bigger.

**Comment by thejameskyle** [comment]
> We can optimize the shadow functions by only creating them for expressions that are outside the returned one.

Sure, that sounds okay by me (although you example is invalid syntax).

I don't think it'd be all that difficult to inline expressions as well. I believe you only need to check that the binding is only referenced in the JSX expression.

```js
function render() {
  let items = [1, 2, 3].map(n => <li>{n}</li>);
  return <ul>{items}</ul>
}
```

```js
function render() {
  return <ul>{[1, 2, 3].map(n => <li>{n}</li>)}</ul>
}
```

**Comment by jridgewell** [comment]
> Sure, that sounds okay by me (although you example is invalid syntax).

I wasn't paying much attention, juggling a few different things (new babel module exporter) in my head. :stuck_out_tongue:

> I don't think it'd be all that difficult to inline expressions as well. I believe you only need to check that the binding is only referenced in the JSX expression.

I think this'll work out pretty nicely.

**Comment by jridgewell** [comment]
Also, any expression that evaluates directly to one of the following — or to an object/array with values that are — will render like you expect. 

```jsx
<div>
  {'string'}
  {new String('string')}
  {123}
  {dom}
</div>
```

**Comment by jridgewell** [comment]
PS. My working branch is [child-assignmentexpressions](https://github.com/babel-plugins/babel-plugin-incremental-dom/compare/child-assignmentexpressions).

**Comment by ivan** [comment]
I want to point out that this will display `1 2 2` in React, and probably `1 2 3` with JSX-as-functions-some-of-the-time.  Users may need to be aware that expressions in their JSX aren't evaluated until later, and may be evaluated more than once.

```js
var i = 1;
var one = <span>{i++}</span>;
var two = <span>{i++}</span>;

React.render(
  <div>{one}<br />{two}<br />{two}</div>,
  document.getElementById('out')
);
```

**Comment by jridgewell** [comment]
> I want to point out that this will display 1 2 2 in React, and probably 1 2 3 with JSX-as-functions-some-of-the-time.

Damn, that's going to be a hard one to fix. Maybe cached references when the variable is mentioned more than once?

Either way, excellent edge case. Thanks!

**Comment by ivan** [comment]
Not sure exactly where you want to cache references, but this case would also exhibit different behavior:

```js
var i = 1;
var one = <span>{i}</span>;
i = 2;
```

and in this case, "lazy JSX" would throw an error:

```js
var f = function() { return "hi" };
var one = <span>{f()}</span>;
f = null;
```

If were were caching based on seeing `f` twice in the function, that wouldn't solve the problem if there were additional indirection.

**Comment by jridgewell** [comment]
Stop finding problems! :stuck_out_tongue_winking_eye: 

How about eager evaluating and replacing the expressions?

```jsx
var i = 1;
var one = <span>{i}</span>;
i = 2;

// - - -

var i = 1;

var _i = i;
var one = function _jsxWrapper() { return <span>{_i}</span>; };
i = 2;
```

```jsx
var f = function() { return "hi" };
var one = <span>{f()}</span>;
f = null;

// - - -

var f = function() { return "hi" };

var _f = f();
var one = function _jxsWrapper() { return <span>{_f}</span>; };
f = null;
```

```jsx
var i = 1;

var _i = i++;
var one = function _jxsWrapper() { return <span>{_i}</span>; };

var _i2 = i++;
var two = function _jxsWrapper() { return <span>{_i2}</span>; };
```

It'll handle most (I think) of the edge cases at the cause of variable allocations. But, only when these happen outside the main `return <jsx />` element.

**Comment by ivan** [comment]
I think that would work.

I don't know if there are any particular complications from having more JSX nested inside a `{ }`, but it might be worth adding a test for that.

**Comment by ivan** [comment]
On another subject, if you use `return` to indicate that you want a DOM object instead of a shadow function, there is a problem in the other direction.   Someone might use a `return` where they shouldn't:

```js
function getUser(name) {
	if(name === 'admin') {
		return <strong>{name}</strong>;
	} else {
		return <span>{name}</span>;
	}
}

var name = 'admin';
patch(document.body, <div>{getUser(name)}</div>);
```

`getUser` returns a DOM object when you needed a shadow function.

As a proposed alternative,  instead of changing behavior on the presence of `return`, always return a shadow function, and as an optional performance optimization, the user can add a `jsxroot` attribute to their root JSX element to indicate that they want a DOM object.

```js
patch(document.body, <div jsxroot>{getUser(name)}</div>);
```

The very-slightly-less-performant alternative would still work, just calling the `<div>` shadow function for the user:

```js
patch(document.body, <div>{getUser(name)}</div>);
```

**Comment by ivan** [comment]
Oops, let me correct that last example

**Comment by ivan** [comment]
(Deleting `return` behavior -> jsxroot attribute proposal until I'm really clear on everything.)

**Comment by jridgewell** [comment]
I think that'll do it. Thanks for pointing out the edge cases @ivan! Can you think of any others?

**Comment by ivan** [comment]
Two others come to mind.  The first is essentially unfixable with the shadow function model; users would just need to be aware of it:

```js
var f = <div>{side_effects()}</div>;
// ... code that assumes side_effects() has already run
```

Also,

```js
var items = [];
for(var i=0; i < 10; i++) {
  items.push(<div>{i}</div>);
}
```

The second one might incorrectly capture 9 for all the items instead of 0 through 9.  Or not, I don't know all the stages that babel will pass that code through and whether the right thing will happen.

**Comment by jridgewell** [comment]
> The first is essentially unfixable with the shadow function model; users would just need to be aware of it:

That one'll actually work.

```jsx
var f = <div>{side_effects()}</div>;

// - - -
var _side_effects = side_effects();
var f = function _jsxWrapper() { return <div>{_side_effects}</div>; }
```

Let me see what I can do about the for-loop, though.

**Comment by ivan** [comment]
Ah, yes, you're right, sorry.

**Comment by jridgewell** [comment]
And, loops weren't hard to support either:

```jsx
for (var i = 0; i < 10; i++) {
  items.push(<div>{i}</div>);
}

// - - -
for (var i = 0; i < 10; i++) {
  items.push((function (_i) {
    function _ref2() {
      elementOpen("div");

      _renderArbitrary(_i);

      return elementClose("div");
    }

    _ref2.__jsxDOMWrapper = true;
    return _ref2;
  })(i));
}
```

**Comment by thejameskyle** [comment]
@jridgewell I'm assuming you're just relying on Babel's [built-in for loop let scoping](http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=let%20items%20%3D%20%5B%5D%3B%0Afor%20(let%20i%20%3D%200%3B%20i%20%3C%2010%3B%20i%2B%2B)%20%7B%0A%20%20items.push(function%20foo()%20%7B%0A%20%20%20%20return%20i%3B%0A%20%20%7D)%0A%7D&playground=false)?

**Comment by jridgewell** [comment]
> I'm assuming you're just relying on Babel's built-in for loop let scoping?

What, how do I do that? I have it manually [creating a closure](https://github.com/babel-plugins/babel-plugin-incremental-dom/blob/child-assignmentexpressions/src/index.js#L201-L210) with any eagerly evaluated expressions now.

**Comment by thejameskyle** [comment]
You could likely just transform `var i` to `let i`

**Comment by jridgewell** [comment]
It should be working (and typing it into the REPL does), but it isn't working during the transformations.

```js
for (var i = 0; i < 10; i++) {
  let _i = i;

  items.push(function _jsxWrapper() {
    text(_i);
  });
}

**Comment by thejameskyle** [comment]
ping @sebmck

**Comment by jridgewell** [comment]
Relevant changes to insert `let`s:

```diff
diff --git a/src/helpers/build-children.js b/src/helpers/build-children.js
index 4aaa599..a514612 100644
--- a/src/helpers/build-children.js
+++ b/src/helpers/build-children.js
@@ -30,7 +30,7 @@ export default function buildChildren(t, scope, file, children, eager) {
       renderArbitraryRef = renderArbitraryRef || injectRenderArbitrary(t, file);
       if (eager) {
         const ref = scope.generateUidIdentifierBasedOnNode(child);
-        children.push(t.variableDeclaration("var", [
+        children.push(t.variableDeclaration("let", [
           t.variableDeclarator(ref, child)
         ]));
         child = ref;
diff --git a/src/index.js b/src/index.js
index c48d8ff..d2e6572 100644
--- a/src/index.js
+++ b/src/index.js
@@ -169,8 +169,8 @@ export default function ({ Plugin, types: t }) {
           elements = filterEagerDeclarators(t, elements, eagerDeclarators);
         }
 
-        if (eagerDeclarators.length && !inExpressionContainer && !(needsWrapper && inLoop)) {
-          let declaration = t.variableDeclaration("var", eagerDeclarators);
+        if (eagerDeclarators.length && !inExpressionContainer) {
+          let declaration = t.variableDeclaration("let", eagerDeclarators);
           if (inAssignment) {
             this.parentPath.parentPath.insertBefore(declaration);
           } else {
@@ -198,20 +198,7 @@ export default function ({ Plugin, types: t }) {
             ref
           ];
 
-          if (inLoop && eagerDeclarators.length) {
-            let paramsAndArgs = partitionDeclarators(eagerDeclarators);
-            element = toFunctionCall(t, t.functionExpression(
-              null,
-              paramsAndArgs.params,
-              t.blockStatement(statementsWithReturnLast(
-                t,
-                flattenExpressions(t, elements)
-              ))
-            ), paramsAndArgs.args);
-
-          } else {
-            element = t.sequenceExpression(elements);
-          }
+          element = t.sequenceExpression(elements);
 
           element._wasJSX = true;
           return element;
```

[Lines 172-179](https://github.com/babel-plugins/babel-plugin-incremental-dom/blob/959e0139f8515cbabfcb41ce818dc25984ca5a6b/src/index.js#L172-L179) do the actual inserting.

The output I'm getting is:

```js
for (var i = 0; i < 10; i++) {
  var _i12 = i;  // Note, this is actually a `let`

  items.push((function _ref2() {
    elementOpen("div");

    _renderArbitrary(_i12);

    return elementClose("div");
  }, _ref2.__jsxDOMWrapper = true, _ref2));
}
```

**Comment by sebmck** [comment]
Do you have a branch with `let` that I can take a look at?

**Comment by jridgewell** [comment]
Just pushed [child-assignments-let](https://github.com/babel-plugins/babel-plugin-incremental-dom/tree/child-assignments-let).

**Comment by jridgewell** [comment]
Also, if I insert a `let` and continue to wrap the element in a closure, it'll detect it and do the proper `let` block scoping. But there'll be two closures then...

**Comment by sebmck** [comment]
What code am I meant to be testing? I'm not clear on what the input is supposed to be and what the actual/expected output is.

**Comment by jridgewell** [comment]
I'm trying to transform a for-loop:

```jsx
for (var i = 0; i < 10; i++) {
  items.push(<div>{i}</div>);
}
```

Now, we're lazy evaluating the JSX, so it'll get wrapped in a function:

```jsx
for (var i = 0; i < 10; i++) {
  items.push(function _jsxWrapper() { return <div>{i}</div>; });
}
```

And, since we're lazy evaluating, all 10 wrapper functions will have the same reference to `i`, which'll be `9` by the time they get evaluated. So, I was creating another closure:

```jsx
for (var i = 0; i < 10; i++) {
  items.push((function(_i) {
    function _jsxWrapper() { return <div>{_i}</div>; }
  }(i));
}
```

If we could instead use a `let` and have babel wrap the body, that would be preferable.

```jsx
for (var i = 0; i < 10; i++) {
  let _i = i;
  items.push(function _jsxWrapper() { return <div>{_i}</div>; });
}

// - - - Babel Transforms to:

function _loop(i) {
  items.push(function _jsxWrapper() { return <div>{i}</div>; });
}

for (var i = 0; i < 10; i++) {
  _loop(i);
}
```

**Comment by sebmck** [comment]
I'm so lost.

```sh
$ cat test.js
for (var i = 0; i < 10; i++) {
  items.push(<div>{i}</div>);
}
$ babel test.js --plugins ./lib
"use strict";

var _hasOwn = Object.prototype.hasOwnProperty;

function _forOwn(object, iterator) {
  for (var prop in object) if (_hasOwn.call(object, prop)) iterator(object[prop], prop);
}

function _renderArbitrary(child) {
  var type = typeof child;

  if (type === "number" || (type === "string" || child && child instanceof String)) {
    text(child);
  } else if (type === "function" && child.__jsxDOMWrapper) {
    child();
  } else if (Array.isArray(child)) {
    child.forEach(_renderArbitrary);
  } else {
    _forOwn(child, _renderArbitrary);
  }
}

for (var i = 0; i < 10; i++) {
  elementOpen("div");

  _renderArbitrary(i);

  return elementClose("div");
}
```

What commands am I supposed to be running?

**Comment by jridgewell** [comment]
Oh, I haven't built on this branch yet. Added a `test.js` file, too.

```bash
$ git checkout child-assignments-let
$ npm run build
$ ./node_modules/.bin/babel test.js --plugins ./lib
```

The for-loop in the output should be block-scoped.

**Comment by sebmck** [comment]
It's because no binding has been registered with that name and those branches have already been crawled so the scope tracking information is already cached. Current solutions are kinda shitty/hacky to register a declaration/binding, especially when it's not already in the tree. I've added an exception to having no binding exist in that case with commit babel/babel@04c2c547001cd7e1e8f8845ff6f199450f9401b0, it's not ideal but it's the easiest.

Also sidenote but instead of using a `__jsxDOMWrapper` property why not just use the `function.name === "__jsxDOMWrapper"`? The current output code wont even work because it's a function expression and wont create a local binding

**Comment by jridgewell** [comment]
I made the change in [04c2c54](https://github.com/babel/babel/commit/04c2c547001cd7e1e8f8845ff6f199450f9401b0) locally, doesn't seem to have fixed it. :frowning:  I just pushed up new code to the same branch, it's been whittled down to the smallest possible example I can think of.

> Also sidenote but instead of using a __jsxDOMWrapper property why not just use the function.name === "__jsxDOMWrapper"

Well this is embarrassing.  I really need to run the compiled code. I was aiming for IE support... I guess I could insert the function beforehand and setter beforehand, and replace with just the unique reference?

**Comment by sebmck** [comment]
> doesn't seem to have fixed it.

Works for me, I get:

```javascript
var items = [];

var _loop = function () {
  var _i = i;

  items.push((function _ref() {
    elementOpen("div");

    _renderArbitrary(_i);

    return elementClose("div");
  }, _ref.__jsxDOMWrapper = true, _ref));
};

for (var i = 0; i < 10; i++) {
  _loop();
}

elementOpen("div");

_renderArbitrary(items);

return elementClose("div");
```

which AFAIK is the desired result.

> I guess I could insert the function beforehand and setter beforehand, and replace with just the unique reference?

Sure, that'd work. Hoisting it so a new one isn't allocated on each iteration would also be a good idea.

**Comment by jridgewell** [comment]
Damn, made the changes to the wrong installed package.

Thanks for helping me debug!
